### ISSUE TITLE
Lineage tab doesn't show any info

### ISSUE THREAD

**Issue by RicardoVilaca** [AltimateAI/vscode-dbt-power-user#1350]
### Expected behavior

When i first downloaded my dbt project, the lineage tab was working fine. But after a few days it shows nothing.

### Actual behavior

Even though having a clean and compiled project, the lineage stopped working.

### Steps To Reproduce

Honestly, i don't know how to reproduce it.

### Log output/Screenshots

![image](https://github.com/user-attachments/assets/609a57da-c9fb-4dfc-aae8-c819a6c62f6b)

### Operating System

Windows

### dbt version

dbt Cloud CLI - 0.38.7

### dbt Adapter

Snowflake

### dbt Power User version

0.43.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
@RicardoVilaca, have you chosen a .sql file in the code editor? It's not clear in the screenshot

**Comment by RicardoVilaca** [comment]
Yes yes, i chose a valid sql file.

![image](https://github.com/user-attachments/assets/1a4b4eaf-4902-452b-a87e-63839d295dbf)

I can also see that the lineage shows correctly on the dbt web editor (same branch, everything up to date).

I ran "dbt compile" as well and everything went smoothly. The project seems to have no issues but the extension can't fetch the lineage.

**Comment by anandgupta42** [comment]
@RicardoVilaca Can you please ping us from the chatbot located in the lower right corner after logging into your SaaS instance? We need more information to debug the issue.

**Comment by RicardoVilaca** [comment]
Sorry, but currently i'm not using the Team version :(

We just tested this extension this week for the first time.

**Comment by anandgupta42** [comment]
You can chat with us here: https://app.myaltimate.com/contactus

**Comment by RicardoVilaca** [comment]
I also noticed this issue

![image](https://github.com/user-attachments/assets/61009b92-5b52-4937-85cd-76b78dc09b81)

**Comment by anandgupta42** [comment]
@RicardoVilaca, we have implemented a fix to address the file path issue. However, we cannot guarantee that this will resolve the original problem of the lineage not displaying. We have included additional logging to aid in identifying the root cause. Please upgrade to the latest version 0.43.4 and let us know if the issue has been resolved.

**Comment by RicardoVilaca** [comment]
Hey @anandgupta42 , this fixed the "ENOENT" issue, but it still didn't fix the lineage problem.

Also i noticed that the datapilot doesn't consider the models as valid

![image](https://github.com/user-attachments/assets/91c1e10f-231c-453f-82b8-7f55d521f8a3)

Although i'm pretty sure that every model is valid because "dbt run" goes without issues until the end

**Comment by RicardoVilaca** [comment]
This issue was fixed today. I can see my lineage again.
Not sure if it was the last patch, or if it was something on my project that changed though..

**Comment by anandgupta42** [comment]
@RicardoVilaca It was because of the last patch. I am glad lineage is working for you now.
