### ISSUE TITLE
DBT project not loading

### ISSUE THREAD

**Issue by Will-Cottrell** [AltimateAI/vscode-dbt-power-user#1371]
### Expected behavior

I can use Power User for dbt features in VS Code

### Actual behavior

Error messages are shown when trying to use features such as Query Results, Compile and Lineage.

### Steps To Reproduce

Power User has recently been working but after reinstalling a virtual environment and updating requirements it has stopped working.

### Log output/Screenshots

![Screenshot 2024-08-14 at 13 56 55](https://github.com/user-attachments/assets/759893a1-9f2e-422c-89ed-d2dcd349f258)
![Screenshot 2024-08-14 at 13 57 02](https://github.com/user-attachments/assets/f4a0b00f-42e3-4344-b112-3ff10d3a6cdd)
![Screenshot 2024-08-14 at 13 57 10](https://github.com/user-attachments/assets/9330cc75-83a6-4842-84d1-327248cd8f88)

### Operating System

Mac OS 14.5 (23F79)

### dbt version

core 1.8.5

### dbt Adapter

bigquery 1.8.2

### dbt Power User version

v0.44.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by kalebkemp** [comment]
I'm having the same issue ☹️ 
with dbt-core 1.8.5
dbt-databricks 1.8.5
power user version v0.44.1
Windows 11

**Comment by anandgupta42** [comment]
@kalebkemp, could you downgrade to version 0.42.X and check if it resolves the issue? Also, both of you are on dbt 1.8.5, which might be causing the problem.

**Comment by mdesmet** [comment]
This error seems related to vscode's Python extension. What happens if you restart vscode, does this error go away?

**Comment by Will-Cottrell** [comment]
Restarted VSCode and reverted power user to v0.42.7 but the issue persists. I fear it is something to do with dbt 1.8.5

**Comment by kalebkemp** [comment]
Mine actually seemingly randomly started working again... I'm not sure what was the exact solution, I did not downgrade. I had restarted vscode, my pc, uninstalled and reinstalled extensions to no avail, but it seemed like after making various changes in my code and pushing/pulling from github it started working... Sorry I can't provide an exact answer on what fixed this..

As a side question: What version of dbt-core would you recommend? Is there some issue with 1.8.5?

**Comment by anandgupta42** [comment]
This may be related to [this issue](https://github.com/microsoft/vscode-python/pull/23939) in the Python extension. The fix was released 3 days ago, and perhaps that's why your environment started working, @kalebkemp. @Will-Cottrell, is this still an issue for you?

**Comment by Will-Cottrell** [comment]
Unfortunately it hasn't fixed it for me, still cannot use Power User

**Comment by c-l-nguyen-blacklane** [comment]
Same for me. I am on Snowflake but the error is the same

**Comment by anandgupta42** [comment]
realted to https://github.com/AltimateAI/vscode-dbt-power-user/issues/1334

**Comment by thebroberts** [comment]
this should be fixed now:
https://github.com/AltimateAI/vscode-dbt-power-user/commit/7c26b3561fb2affd286aa1b8d3bbd00c34c1226e
#1379

**Comment by Will-Cottrell** [comment]
Have checked this morning and I still cannot load a dbt project 😢

**Comment by anandgupta42** [comment]
@Will-Cottrell What's the version of extension installed on your machine?

**Comment by anandgupta42** [comment]
this is duplicate of #1334

**Comment by Will-Cottrell** [comment]
Completely uninstalling VSCode, removing files and settings and reinstalling has fixed the issue.
