### ISSUE TITLE
Add ability to disable notifications

### ISSUE THREAD

**Issue by ivan-toriya-precis** [AltimateAI/vscode-dbt-power-user#407]
### Describe the feature

I want to disable irrelevant notifications, that I see after every VSCode startup.
![image](https://user-images.githubusercontent.com/109348848/232490585-c2a41954-e243-497c-b7e7-d4d2fab5961b.png)

Why these errors irrelevant for me?
* `An error occured while initializing the dbt project: Runtime Error Credentials in profile "dbt_[clientname]", target "dev" invalid: ['project_id'] is not valid under any of the given schemas`
I'm using one project directory as a template for creating new projects
* `An error occured while initializing the dbt project: Runtime Error dbt cannot run because no profile was specified for this dbt project. To specify a profile for this project, add a line like the this to your dbt_project.yml file: profile: [profile name] Here, [profile name] should be replaced with a profile name defined in your profiles.yml file. You can find profiles.yml here: /home/ivantoriya-ubuntu20_04_4/.dbt/profiles.yml`
same as above + I'm storing profiles in a different way
* `dbt Power User detected 17 projects in your work space, this will negatively affect performance.`
My performance not affected 

### Describe alternatives you've considered

* It can't be done in VSCode settings.
* I don't want to change my setup, because of that.

### Who will benefit?

Me, my team, and someone else with a similar issue.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
> dbt Power User detected 17 projects in your work space, this will negatively affect performance.
> My performance not affected

I think we can bump it to 20, the memory usage is about 100Mb per project as we run a separate process per project.

the other issues can probably be resolved with something like https://stackoverflow.com/questions/33258543/how-to-exclude-folder-from-explore-tab

**Comment by ivan-toriya-precis** [comment]
> the other issues can probably be resolved with something like https://stackoverflow.com/questions/33258543/how-to-exclude-folder-from-explore-tab

I don't want to exclude the folder from the Explorer tab

**Comment by geo909** [comment]
Every time I update the extension, I'm getting a notification about whether I'd like help to setup the extension. I've finished this in the past, but I'm still getting this. It is very annoying. I'd love to have an option of disabling this notification.

**Comment by anandgupta42** [comment]
@geo909 Is the notification not going away after you click on ignore? Also, which version of the extension are you using?

**Comment by geo909** [comment]
@anandgupta42 Thanks for the quick reply!

Yes, I believe so, I clicked ignore in the past and/or completed the procedure and it still appeared between updates.

I'm quite sure about that, but let me confirm next time I update. My current version is 0.24.3 but I update regularly.

**Comment by geo909** [comment]
@anandgupta42 It's actually worse than I though, the notification is there every time I just open up VSCode..

**Comment by anandgupta42** [comment]
@geo909 Can you please send us a message at https://app.myaltimate.com/contactus so we can help you resolve the issue?
